version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:6.2
    ports:
      - "6379:6379"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "request.count:1:1"

  external-service:
    image: nbhardwaj/external-service
    ports:
      - "8081:8081"
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64

  api:
    image: nbhardwaj/request-api
    ports:
      - "8080:8082"
    restart: always
    depends_on:
      - kafka
      - redis
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - REQUESTCOUNT_SERVICE_URL=http://external-service:8081/external/api/
      - ENABLE_SCHEDULE=true
      - AUTO_CREATE_TOPICS_ENABLE=true
      - SERVER_PORT=8082
      - SPRING_KAFKA_PRODUCER_BOOTSTRAPSERVERS=kafka:9092